server:
  address: ${SERVER_ADDRESS:localhost}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:/app/db/medication-service
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

mymeds:
  url:
    fe-qr-base-url: http://${MY_ADDRESS}:3000/user-medications/public
    user-service-base-url: http://app-mymeds-user-service-1:8020/api/v1
    auth-service-base-url: http://app-mymeds-auth-service-1:8010/api/v1