server:
  address: ${SERVER_ADDRESS:localhost}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:/app/db/user-service
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

regex:
  password: ^.{4,}$
jwt:
  expiration: 120000

mymeds:
  url:
    auth-service: http://app-mymeds-auth-service-1:8010/api/v1