server:
  address: ${SERVER_ADDRESS:localhost}
spring:
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:/app/db/auth-service
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console

mymeds:
  url:
    user-service-base-url: http://app-mymeds-user-service-1:8020/api/v1
    medication-service-base-url: http://app-mymeds-medication-service-1:8030/api/v1
    notification-service-base-url: http://app-mymeds-notification-service-1:8040/api/v1

regex:
  password: ^.{4,}$