server:
 address: ${SERVER_ADDRESS:localhost}
mymeds:
 url:
  fe-base-url: http://${MY_ADDRESS}:3000
  auth-service-base-url: http://app-mymeds-auth-service-1:8010
  user-service-base-url: http://app-mymeds-user-service-1:8020
  medication-service-base-url: http://app-mymeds-medication-service-1:8030